(lang dune 3.20)

(name magda-compiler)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Agnano Loris <loris.agnano@gmail.com>"
         "Bocale Mattia <mattia.bocale@edu.unito.it>"
         "De Matteis Francesco <francescodematteis03@gmail.com>")

(maintainers "Agnano Loris <loris.agnano@gmail.com>"
             "Bocale Mattia <mattia.bocale@edu.unito.it>"
             "De Matteis Francesco <francescodematteis03@gmail.com>")

(license AFL-3.0)

(documentation https://url/to/documentation)

(package
 (name magda-compiler)
 (synopsis "Compiler for the Magda Language")
 (description "This Project is used to compile programs that use Magda as language")
 (depends ocaml)
 (tags
  ("Magda" "Compiler" "sua padella" "Beppe Vessicchio")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
